name: murmurhash
description: MurmurHash v3 Implementation in Dart.
version: 1.0.0
repository: https://github.com/HosseinYousefi/murmurhash

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'

dependencies:

dev_dependencies:
  test: