name: murmurhash
description: MurmurHash v3 Implementation in Dart.
version: 1.0.1
repository: https://github.com/HosseinYousefi/murmurhash

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:

dev_dependencies:
  test: